### ISSUE TITLE
Wearable emissive in testing, not emissive after publishing.

### ISSUE THREAD

**Issue by StinkyScrublet** [decentraland/catalyst#614] opened 2021-08-19 07:54 UTC
https://opensea.io/assets/matic/0x8209db483dceb4f23e4922d93c587022e1d47e01/5

This wearable appeared emissive in testing and in it's thumbnail. After being published it doesn't emit at all.

I understand there had been many glitches with shrunken heads and other things, not sure if this is related to those issues.

**Comment by agusaldasoro** [comment] 2021-08-20 17:16
Duplicate of https://github.com/decentraland/unity-renderer/issues/1006 

Hi @StinkyScrublet, thanks for reporting this! This issue is being tracked.

**Closed** 2021-08-20 17:16 UTC
